// ---------------------------------------------------------------------------
// Server-side PDF rendering for Governance Pack documents
// ---------------------------------------------------------------------------
// Uses jsPDF directly (no DOM/html2canvas). Returns Uint8Array PDF bytes.

import jsPDF from "jspdf";

// ---- Colour constants -----------------------------------------------------

const BRAND_COLOR: [number, number, number] = [37, 99, 235];
const TEXT_COLOR: [number, number, number] = [17, 24, 39];
const MUTED_COLOR: [number, number, number] = [107, 114, 128];
const RED: [number, number, number] = [220, 38, 38];
const AMBER: [number, number, number] = [217, 119, 6];
const GREEN: [number, number, number] = [22, 163, 74];

// ---- Layout constants -----------------------------------------------------

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const MARGIN_TOP = 20;
const MARGIN_BOTTOM = 25;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
const MAX_Y = PAGE_HEIGHT - MARGIN_BOTTOM;

// ---- Helpers --------------------------------------------------------------

function addPageBreakIfNeeded(doc: jsPDF, y: number, needed = 12): number {
  if (y + needed > MAX_Y) {
    doc.addPage();
    return MARGIN_TOP;
  }
  return y;
}

function addHeader(
  doc: jsPDF,
  title: string,
  orgName: string,
  version: number,
  date: string,
): number {
  let y = MARGIN_TOP;

  // "VERISUM" brand mark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...BRAND_COLOR);
  doc.text("VERISUM", MARGIN_LEFT, y);
  y += 10;

  // Document title
  doc.setFontSize(18);
  doc.setTextColor(...TEXT_COLOR);
  doc.text(title, MARGIN_LEFT, y);
  y += 8;

  // Org | version | date line
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...MUTED_COLOR);
  doc.text(`${orgName}  |  Version ${version}  |  ${date}`, MARGIN_LEFT, y);
  y += 4;

  // Blue divider
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_LEFT, y, PAGE_WIDTH - MARGIN_RIGHT, y);
  y += 10;

  return y;
}

function addWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    y = addPageBreakIfNeeded(doc, y, lineHeight);
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

function addPageFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED_COLOR);
    const footerText = `Generated by Verisum AI Governance  |  Page ${i} of ${pageCount}`;
    const tw = doc.getTextWidth(footerText);
    doc.text(footerText, (PAGE_WIDTH - tw) / 2, PAGE_HEIGHT - 12);
  }
}

/**
 * Minimal markdown-to-PDF renderer.
 * Handles: # / ## / ### headings, bullet lists (- / * ), numbered lists,
 * blank lines (spacing), and plain paragraphs.
 */
function renderMarkdownSimple(doc: jsPDF, md: string, startY: number): number {
  let y = startY;
  const lines = md.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];

    // ---- Blank line = spacing ----
    if (raw.trim() === "") {
      y += 4;
      continue;
    }

    // ---- H1 ----
    if (raw.startsWith("# ")) {
      y = addPageBreakIfNeeded(doc, y, 14);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(...TEXT_COLOR);
      y = addWrappedText(doc, raw.slice(2).trim(), MARGIN_LEFT, y, CONTENT_WIDTH, 7);
      y += 3;
      continue;
    }

    // ---- H2 ----
    if (raw.startsWith("## ")) {
      y = addPageBreakIfNeeded(doc, y, 12);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(...TEXT_COLOR);
      y = addWrappedText(doc, raw.slice(3).trim(), MARGIN_LEFT, y, CONTENT_WIDTH, 6);
      y += 2;
      continue;
    }

    // ---- H3 ----
    if (raw.startsWith("### ")) {
      y = addPageBreakIfNeeded(doc, y, 10);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...TEXT_COLOR);
      y = addWrappedText(doc, raw.slice(4).trim(), MARGIN_LEFT, y, CONTENT_WIDTH, 5);
      y += 2;
      continue;
    }

    // ---- Bullet list (- or * ) ----
    const bulletMatch = raw.match(/^(\s*)[-*]\s+(.*)/);
    if (bulletMatch) {
      y = addPageBreakIfNeeded(doc, y, 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_COLOR);
      const indent = Math.min(bulletMatch[1].length, 8) * 2;
      const bulletX = MARGIN_LEFT + 4 + indent;
      const textX = bulletX + 4;
      const maxW = CONTENT_WIDTH - (textX - MARGIN_LEFT);
      doc.text("\u2022", bulletX, y);
      y = addWrappedText(doc, bulletMatch[2].trim(), textX, y, maxW, 5);
      continue;
    }

    // ---- Numbered list (1. / 2. etc.) ----
    const numMatch = raw.match(/^(\s*)(\d+)\.\s+(.*)/);
    if (numMatch) {
      y = addPageBreakIfNeeded(doc, y, 6);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_COLOR);
      const indent = Math.min(numMatch[1].length, 8) * 2;
      const numX = MARGIN_LEFT + 4 + indent;
      const textX = numX + 6;
      const maxW = CONTENT_WIDTH - (textX - MARGIN_LEFT);
      doc.text(`${numMatch[2]}.`, numX, y);
      y = addWrappedText(doc, numMatch[3].trim(), textX, y, maxW, 5);
      continue;
    }

    // ---- Plain paragraph ----
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_COLOR);
    y = addWrappedText(doc, raw.trim(), MARGIN_LEFT, y, CONTENT_WIDTH, 5);
  }

  return y;
}

// ---- Exported generators --------------------------------------------------

/**
 * Renders the AI Governance Statement markdown as a branded PDF.
 */
export function generateGovernanceStatementPdf(
  statementMd: string,
  orgName: string,
  version: number,
): Uint8Array {
  const doc = new jsPDF("p", "mm", "a4");
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let y = addHeader(doc, "AI Governance Statement", orgName, version, date);
  renderMarkdownSimple(doc, statementMd, y);
  addPageFooters(doc);

  return new Uint8Array(doc.output("arraybuffer"));
}

/**
 * Renders the AI Usage Inventory (company + tools table + vendors) as PDF.
 */
export function generateUsageInventoryPdf(
  inventoryJson: {
    company: {
      name: string;
      industry: string;
      headcount: string;
      jurisdiction: string;
    };
    tools: Array<{
      name: string;
      purpose: string;
      dataClassification: string;
      departments: string;
    }>;
    additionalVendors: Array<{
      vendor_name: string;
      risk_category: string;
    }>;
  },
  orgName: string,
  version: number,
): Uint8Array {
  const doc = new jsPDF("p", "mm", "a4");
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let y = addHeader(doc, "AI Usage Inventory", orgName, version, date);

  // ---- Organisation Details section ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("Organisation Details", MARGIN_LEFT, y);
  y += 7;

  const company = inventoryJson.company;
  const details: [string, string][] = [
    ["Company", company.name],
    ["Industry", company.industry],
    ["Headcount", company.headcount],
    ["Jurisdiction", company.jurisdiction],
  ];

  doc.setFontSize(10);
  for (const [label, value] of details) {
    y = addPageBreakIfNeeded(doc, y, 6);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...MUTED_COLOR);
    doc.text(`${label}:`, MARGIN_LEFT, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT_COLOR);
    doc.text(value || "N/A", MARGIN_LEFT + 30, y);
    y += 6;
  }
  y += 6;

  // ---- AI Tools table ----
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...TEXT_COLOR);
  doc.text("AI Tools", MARGIN_LEFT, y);
  y += 7;

  // Column widths for tools table
  const toolCols = [38, 50, 38, 44]; // Tool | Purpose | Classification | Departments
  const toolHeaders = ["Tool", "Purpose", "Data Classification", "Departments"];

  y = drawTableHeader(doc, toolHeaders, toolCols, MARGIN_LEFT, y);
  y = drawToolRows(doc, inventoryJson.tools, toolCols, MARGIN_LEFT, y);

  y += 8;

  // ---- Vendor Register Summary (if any) ----
  if (inventoryJson.additionalVendors && inventoryJson.additionalVendors.length > 0) {
    y = addPageBreakIfNeeded(doc, y, 20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...TEXT_COLOR);
    doc.text("Vendor Register Summary", MARGIN_LEFT, y);
    y += 7;

    const vendorCols = [85, 85];
    const vendorHeaders = ["Vendor", "Risk Category"];

    y = drawTableHeader(doc, vendorHeaders, vendorCols, MARGIN_LEFT, y);
    y = drawVendorRows(doc, inventoryJson.additionalVendors, vendorCols, MARGIN_LEFT, y);
  }

  addPageFooters(doc);
  return new Uint8Array(doc.output("arraybuffer"));
}

/**
 * Renders the Risk & Gap Summary markdown as a branded PDF.
 */
export function generateGapAnalysisPdf(
  gapMd: string,
  orgName: string,
  version: number,
): Uint8Array {
  const doc = new jsPDF("p", "mm", "a4");
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  let y = addHeader(doc, "Risk & Gap Summary", orgName, version, date);
  renderMarkdownSimple(doc, gapMd, y);
  addPageFooters(doc);

  return new Uint8Array(doc.output("arraybuffer"));
}

// ---- Table drawing helpers ------------------------------------------------

function drawTableHeader(
  doc: jsPDF,
  headers: string[],
  colWidths: number[],
  startX: number,
  y: number,
): number {
  y = addPageBreakIfNeeded(doc, y, 10);
  const rowH = 8;

  // Grey header background
  doc.setFillColor(243, 244, 246); // gray-100
  const totalW = colWidths.reduce((a, b) => a + b, 0);
  doc.rect(startX, y - 5, totalW, rowH, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_COLOR);

  let x = startX + 2;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x, y);
    x += colWidths[i];
  }

  // Bottom border
  doc.setDrawColor(209, 213, 219); // gray-300
  doc.setLineWidth(0.3);
  doc.line(startX, y + 3, startX + totalW, y + 3);

  return y + rowH;
}

function drawToolRows(
  doc: jsPDF,
  tools: Array<{
    name: string;
    purpose: string;
    dataClassification: string;
    departments: string;
  }>,
  colWidths: number[],
  startX: number,
  y: number,
): number {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_COLOR);

  const totalW = colWidths.reduce((a, b) => a + b, 0);

  for (const tool of tools) {
    y = addPageBreakIfNeeded(doc, y, 8);
    const values = [
      tool.name || "",
      tool.purpose || "",
      tool.dataClassification || "",
      tool.departments || "",
    ];

    let x = startX + 2;
    for (let i = 0; i < values.length; i++) {
      // Truncate if too long for the cell
      const maxChars = Math.floor(colWidths[i] / 1.8);
      const text =
        values[i].length > maxChars
          ? values[i].slice(0, maxChars - 1) + "\u2026"
          : values[i];
      doc.text(text, x, y);
      x += colWidths[i];
    }

    // Row border
    doc.setDrawColor(229, 231, 235); // gray-200
    doc.setLineWidth(0.2);
    doc.line(startX, y + 3, startX + totalW, y + 3);
    y += 7;
  }

  return y;
}

function riskColor(category: string): [number, number, number] {
  const lower = (category || "").toLowerCase();
  if (lower === "minimal" || lower === "limited") return GREEN;
  if (lower === "high") return AMBER;
  if (lower === "unacceptable") return RED;
  return MUTED_COLOR; // unassessed or unknown
}

function drawVendorRows(
  doc: jsPDF,
  vendors: Array<{ vendor_name: string; risk_category: string }>,
  colWidths: number[],
  startX: number,
  y: number,
): number {
  doc.setFontSize(8);
  const totalW = colWidths.reduce((a, b) => a + b, 0);

  for (const vendor of vendors) {
    y = addPageBreakIfNeeded(doc, y, 8);

    // Vendor name
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...TEXT_COLOR);
    doc.text(vendor.vendor_name || "Unknown", startX + 2, y);

    // Risk category (colour-coded)
    const risk = vendor.risk_category || "unassessed";
    doc.setTextColor(...riskColor(risk));
    doc.setFont("helvetica", "bold");
    doc.text(risk.charAt(0).toUpperCase() + risk.slice(1), startX + colWidths[0] + 2, y);

    // Row border
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.2);
    doc.line(startX, y + 3, startX + totalW, y + 3);
    y += 7;
  }

  return y;
}
